### ISSUE TITLE
Exceptions on startup

### ISSUE THREAD

**Issue by erip** [mitre/callisto#1]
I just installed Callisto 1.8 with the installer from the github pages site.

In `$CALLISTO_HOME` I issued `java -jar Callisto.jar` and got the following:

```
Callisto v1.8-release - (c) 2002-2013 The MITRE Corporation

Java version: 1.8.0_60
Callisto Home        = /Applications/Callisto
Callisto Tasks Dir   = /Applications/Callisto/tasks
Creating Personal Home directory for Callisto

Unable to log to directory: null
    java.lang.NullPointerException

java.lang.NullPointerException
    at java.io.File.<init>(File.java:277)
    at org.mitre.jawb.JawbLogger.<init>(JawbLogger.java:653)
    at org.mitre.jawb.Jawb.initLog(Jawb.java:417)
    at org.mitre.jawb.Jawb.main(Jawb.java:368)
Scanning Task Directory: /Applications/Callisto/tasks
  Loading org.mitre.ace2004.callisto.ACE2004Task
AbstractTask.constr taskName = org.mitre.ace2004
   Ready: ACE Event Task (5.0.3.0) [org.mitre.ace2004]
  Loading org.mitre.bioinfo.callisto.BioInfoTask
AbstractTask.constr taskName = org.mitre.bioinfo
   Ready: BioInformatics Task (1.0) [org.mitre.bioinfo]
  Loading org.mitre.coref.callisto.CorefTask
AbstractTask.constr taskName = org.mitre.coref
   Ready: Coref Task (1.2) [org.mitre.coref]
  Loading org.mitre.edc.callisto.EDCTask
AbstractTask.constr taskName = org.mitre.edc
   Ready: EDC Task (1.0) [org.mitre.edc]
  Loading org.mitre.eeld.callisto.EELDTask
AbstractTask.constr taskName = org.mitre.eeld
   Ready: EELD Task (1.0) [org.mitre.eeld]
  Loading org.mitre.muc.callisto.MUCTask
AbstractTask.constr taskName = org.mitre.muc
   Ready: MUC Task (1.3) [org.mitre.muc]
  Loading org.mitre.muc.callisto.MUCOtherTask
AbstractTask.constr taskName = org.mitre.muc.other
   Ready: MUC+Other Task (1.0) [org.mitre.muc.other]
  Loading org.mitre.muc.callisto.MUCTranslatorTask
AbstractTask.constr taskName = org.mitre.muc.translator
   Ready: MUC-Translator's Task (1.0) [org.mitre.muc.translator]
  Loading org.mitre.muc.callisto.MUCFinTask
AbstractTask.constr taskName = org.mitre.muc.fin
   Ready: MUC+Fin Task (1.0) [org.mitre.muc.fin]
  Loading org.mitre.muc.callisto.MUCCustomTask
AbstractTask.constr taskName = org.mitre.muc.custom
No types file preference foundtask.org.mitre.muc.custom.typesfile
   Ready: MUCCustom Task (1.3) [org.mitre.muc.custom]
  Loading org.mitre.muc.callisto.MUCRolesTask
AbstractTask.constr taskName = org.mitre.muc.roles
MUCRolesTask: name= org.mitre.muc.rolesTASK_NAME= org.mitre.muc.roles
No types file preference foundtask.org.mitre.muc.roles.typesfile
   Ready: MUCRoles Task (1.3) [org.mitre.muc.roles]

Failed to load Task: org.mitre.muc.callisto.MUCMixedTask
java.lang.ClassNotFoundException: org.mitre.muc.callisto.MUCMixedTask
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at org.mitre.jawb.tasks.TaskManager.loadTask(TaskManager.java:344)
    at org.mitre.jawb.tasks.TaskManager.loadTaskJar(TaskManager.java:250)
    at org.mitre.jawb.tasks.TaskManager.scanTaskDir(TaskManager.java:185)
    at org.mitre.jawb.Jawb.initTasks(Jawb.java:2119)
    at org.mitre.jawb.Jawb.main(Jawb.java:374)
  Loading org.mitre.rdc.callisto.RDCTask
AbstractTask.constr taskName = org.mitre.rdc
   Ready: RDC Task (1.3) [org.mitre.rdc]
  Loading org.mitre.callisto.sample.SampleTask
AbstractTask.constr taskName = org.mitre.sample
   Ready: Sample (1.0) [org.mitre.sample]
  Loading org.mitre.sentence.callisto.SentenceTask
AbstractTask.constr taskName = org.mitre.sentence
   Ready: Sentence Task (1.0) [org.mitre.sentence]
  Loading org.mitre.spatialml.callisto.SpatialMLTask
AbstractTask.constr taskName = org.mitre.spatialml
AbstractTask.constr taskName = org.mitre.spatialml
   Ready: SpatialML Task (0.10.2) [org.mitre.spatialml]
  Loading org.mitre.tango.callisto.TangoTask
AbstractTask.constr taskName = org.mitre.tango.timeml
   Ready: Tango TimeML (1.0) [org.mitre.tango.timeml]
  Loading org.mitre.timex2.callisto.TIMEX2Task
AbstractTask.constr taskName = org.mitre.timex2
   Ready: TIMEX2 Task (1.2) [org.mitre.timex2]
```

Has anyone else encountered these `ClassNotFoundExceptions` or `NullPointerExceptions`? I'm using OS X 10.11.

**Comment by robyn-kozierok** [comment]
What kind of machine are you working on?

Try going into .callisto/callisto.prefs in your homedir and setting 
log.path to a writable location.

**Comment by erip** [comment]
@robyn-kozierok I'm using a Mac (OS X 10.11). I set the `log.path` so now I'm not getting the `NullPointerException`, but I'm still getting the `ClassNotFoundException` for `org.mitre.muc.callisto.MUCMixedTask`.

**Comment by robyn-kozierok** [comment]
Does that prevent Callisto from starting up?

**Comment by erip** [comment]
@robyn-kozierok It doesn't, but it's a bit unexpected for an exception to arise unless something is going wrong.

**Comment by robyn-kozierok** [comment]
I'm not sure why you're encountering that exception, but if you don't need that particular task, it shouldn't be an issue.
